### ISSUE TITLE
Chapter 7: ConvertSaveload requires serde as a dependency.

### ISSUE THREAD

**Issue by Bobbias** [thebracket/rustrogueliketutorial#214]
While following along with chapter 7, I encountered a bunch of errors related to the use of the derive macro `ConvertSaveload` on the `WantsToMelee` component.

Further, nowhere in the tutorial does it explain that this will require serde as a dependency. I had to add the following to my cargo.toml:

```toml
[dependencies]
rltk = { git = "https://github.com/amethyst/bracket-lib" }
specs = { version = "0.17", features = ["serde"] } # added features = "serde"
serde = "1.0" # added serde dependency
```

Using the git version of rltk as per amethyst/bracket-lib#301
I also had to manually add the following additional imports:

```rust
use specs::saveload::{ConvertSaveload, Marker};
use specs::error::NoError;
use serde::{Serialize, Deserialize};
```

Failing to do so results in a series of complaints that various traits cannot be found. I'm still pretty new to rust, but I get the feeling that I shouldn't need to manually bring all of these traits into scope. I assume that this is the result of something not quite working right on the side of specs or specs-derive. 

My suggestion would be to either remove the use of ConvertSaveload, or add clear instructions detailing the additional changes necessary to compile from that point on.
